name: Compilar Mac y Windows

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'v1.0.0-beta'
        required: true
        default: 'v1.0.0-beta'

jobs:
  build-and-upload:
    permissions:
      contents: write
    
    environment: '.env' 
    
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # 🚀 Actualizado a Node 22 para cumplir con Vite

      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Instalar dependencias de Node
        run: npm ci # 🛠️ Cambiado a 'npm ci' para una instalación limpia y exacta en CI

      - name: Compilar y añadir a la Release existente
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
        with:
          tagName: ${{ github.event.inputs.tag }}
          releaseDraft: false
          prerelease: false
